//
//  GLESBC_Shims.h
//  GLES Backwards Compatibility
//
//  Created by Chinmay Garde on 1/12/12.
//  Copyright (c) 2012 Carnegie Mellon University. All rights reserved.
//

#ifndef GLES_Backwards_Compatibility_GLESBC_Shims_h
#define GLES_Backwards_Compatibility_GLESBC_Shims_h

#define glActiveTexture glActiveTextureBC
#define glAlphaFunc glAlphaFuncBC
#define glAlphaFuncx glAlphaFuncxBC
#define glBindTexture glBindTextureBC
#define glBlendFunc glBlendFuncBC
#define glClear glClearBC
#define glClearColor glClearColorBC
#define glClearColorx glClearColorxBC
#define glClearDepthf glClearDepthfBC
#define glClearDepthx glClearDepthxBC
#define glClearStencil glClearStencilBC
#define glClientActiveTexture glClientActiveTextureBC
#define glColor4f glColor4fBC
#define glColor4x glColor4xBC
#define glColorMask glColorMaskBC
#define glColorPointer glColorPointerBC
#define glCompressedTexImage2D glCompressedTexImage2DBC
#define glCompressedTexSubImage2D glCompressedTexSubImage2DBC
#define glCopyTexImage2D glCopyTexImage2DBC
#define glCopyTexSubImage2D glCopyTexSubImage2DBC
#define glCullFace glCullFaceBC
#define glDeleteTextures glDeleteTexturesBC
#define glDepthFunc glDepthFuncBC
#define glDepthMask glDepthMaskBC
#define glDepthRangef glDepthRangefBC
#define glDepthRangex glDepthRangexBC
#define glDisable glDisableBC
#define glDisableClientState glDisableClientStateBC
#define glDrawArrays glDrawArraysBC
#define glDrawElements glDrawElementsBC
#define glEnable glEnableBC
#define glEnableClientState glEnableClientStateBC
#define glFinish glFinishBC
#define glFlush glFlushBC
#define glFogf glFogfBC
#define glFogfv glFogfvBC
#define glFogx glFogxBC
#define glFogxv glFogxvBC
#define glFrontFace glFrontFaceBC
#define glFrustumf glFrustumfBC
#define glFrustumx glFrustumxBC
#define glGenTextures glGenTexturesBC
#define glGetError glGetErrorBC
#define glGetIntegerv glGetIntegervBC
#define GLubyte GLubyteBC
#define glHint glHintBC
#define glLightModelf glLightModelfBC
#define glLightModelfv glLightModelfvBC
#define glLightModelx glLightModelxBC
#define glLightModelxv glLightModelxvBC
#define glLightf glLightfBC
#define glLightfv glLightfvBC
#define glLightx glLightxBC
#define glLightxv glLightxvBC
#define glLineWidth glLineWidthBC
#define glLineWidthx glLineWidthxBC
#define glLoadIdentity glLoadIdentityBC
#define glLoadMatrixf glLoadMatrixfBC
#define glLoadMatrixx glLoadMatrixxBC
#define glLogicOp glLogicOpBC
#define glMaterialf glMaterialfBC
#define glMaterialfv glMaterialfvBC
#define glMaterialx glMaterialxBC
#define glMaterialxv glMaterialxvBC
#define glMatrixMode glMatrixModeBC
#define glMultMatrixf glMultMatrixfBC
#define glMultMatrixx glMultMatrixxBC
#define glMultiTexCoord4f glMultiTexCoord4fBC
#define glMultiTexCoord4x glMultiTexCoord4xBC
#define glNormal3f glNormal3fBC
#define glNormal3x glNormal3xBC
#define glNormalPointer glNormalPointerBC
#define glOrthof glOrthofBC
#define glOrthox glOrthoxBC
#define glPixelStorei glPixelStoreiBC
#define glPointSize glPointSizeBC
#define glPointSizex glPointSizexBC
#define glPolygonOffset glPolygonOffsetBC
#define glPolygonOffsetx glPolygonOffsetxBC
#define glPopMatrix glPopMatrixBC
#define glPushMatrix glPushMatrixBC
#define glReadPixels glReadPixelsBC
#define glRotatef glRotatefBC
#define glRotatex glRotatexBC
#define glSampleCoverage glSampleCoverageBC
#define glSampleCoveragex glSampleCoveragexBC
#define glScalef glScalefBC
#define glScalex glScalexBC
#define glScissor glScissorBC
#define glShadeModel glShadeModelBC
#define glStencilFunc glStencilFuncBC
#define glStencilMask glStencilMaskBC
#define glStencilOp glStencilOpBC
#define glTexCoordPointer glTexCoordPointerBC
#define glTexEnvf glTexEnvfBC
#define glTexEnvfv glTexEnvfvBC
#define glTexEnvx glTexEnvxBC
#define glTexEnvxv glTexEnvxvBC
#define glTexImage2D glTexImage2DBC
#define glTexParameterf glTexParameterfBC
#define glTexParameterx glTexParameterxBC
#define glTexSubImage2D glTexSubImage2DBC
#define glTranslatef glTranslatefBC
#define glTranslatex glTranslatexBC
#define glVertexPointer glVertexPointerBC
#define glViewport glViewportBC
#define glBindBuffer glBindBufferBC
#define glBufferData glBufferDataBC
#define glBufferSubData glBufferSubDataBC
#define glClipPlanef glClipPlanefBC
#define glClipPlanex glClipPlanexBC
#define glColor4ub glColor4ubBC
#define glDeleteBuffers glDeleteBuffersBC
#define glGenBuffers glGenBuffersBC
#define glGetClipPlanef glGetClipPlanefBC
#define glGetFloatv glGetFloatvBC
#define glGetLightfv glGetLightfvBC
#define glGetLightxv glGetLightxvBC
#define glGetMaterialfv glGetMaterialfvBC
#define glGetMaterialxv glGetMaterialxvBC
#define glGetTexEnvfv glGetTexEnvfvBC
#define glGetTexEnviv glGetTexEnvivBC
#define glGetTexEnvxv glGetTexEnvxvBC
#define glGetTexParameterfv glGetTexParameterfvBC
#define glGetTexParameteriv glGetTexParameterivBC
#define glGetTexParameterxv glGetTexParameterxvBC
#define glGetBooleanv glGetBooleanvBC
#define glGetFixedv glGetFixedvBC
#define glGetPointerv glGetPointervBC
#define glIsBuffer glIsBufferBC
#define glIsEnabled glIsEnabledBC
#define glIsTexture glIsTextureBC
#define glPointParameterf glPointParameterfBC
#define glPointParameterfv glPointParameterfvBC
#define glPointParameterx glPointParameterxBC
#define glPointParameterxv glPointParameterxvBC
#define glTexEnvi glTexEnviBC
#define glTexEnviv glTexEnvivBC
#define glTexParameteri glTexParameteriBC
#define glTexParameteriv glTexParameterivBC
#define glCurrentPaletteMatrixOES glCurrentPaletteMatrixOESBC
#define glLoadPaletteFromModelViewMatrixOES glLoadPaletteFromModelViewMatrixOESBC
#define glMatrixIndexPointerOES glMatrixIndexPointerOESBC
#define glWeightPointerOES glWeightPointerOESBC
#define glPointSizePointerOES glPointSizePointerOESBC
#define glDrawTexsOES glDrawTexsOESBC
#define glDrawTexiOES glDrawTexiOESBC
#define glDrawTexxOES glDrawTexxOESBC
#define glDrawTexsvOES glDrawTexsvOESBC
#define glDrawTexivOES glDrawTexivOESBC
#define glDrawTexxvOES glDrawTexxvOESBC
#define glDrawTexfOES glDrawTexfOESBC
#define glDrawTexfvOES glDrawTexfvOESBC


#endif
